const Arrayism = require('arrayism');
const Stringo = require('stringo');

const string = {
	breakStr: Stringo.breakStr,
	changeCase: Stringo.changeCase,
	chunk: Stringo.chunk,
	clear: Stringo.clear,
	count: Stringo.count,
	distance: Stringo.distance,
	has: Stringo.has,
	insertBefore: Stringo.insert.insertBefore,
	insertAfter: Stringo.insert.insertAfter,
	join: Stringo.join,
	nth: Stringo.nth,
	random: Stringo.random,
	remove: Stringo.remove,
	removeWhitespace: Stringo.removeWhitespace,
	reverse: Stringo.reverse,
	shuffle: Stringo.shuffle,
	StringortChars: Stringo.sort.sortChars,
	StringortWords: Stringo.sort.sortWords,
	unique: Stringo.unique,
	words: Stringo.words,
	isAlnum: Stringo.isAlnum,
	isAlpha: Stringo.isAlpha,
	isDigit: Stringo.isDigit,
	isLower: Stringo.isLower,
	isUpper: Stringo.isUpper,
	isSentence: Stringo.isSentence
}

const array = {
	asort: Arrayism.sort.asort,
	average: Arrayism.math.average,
	changeCase: Arrayism.changeCase,
	chunk: Arrayism.chunk,
	clean: Arrayism.clean,
	clear: Arrayism.clear,
	clone: Arrayism.clone,
	count: Arrayism.count,
	difference: Arrayism.math.difference,
	dimension: Arrayism.dimension,
	distance: Arrayism.distance,
	dsort: Arrayism.sort.dsort,
	filter: Arrayism.filter,
	flatten: Arrayism.flatten,
	getValues: Arrayism.getValues,
	getArrayInfo: Arrayism.getArrayInfo,
	getPiece: Arrayism.getPiece,
	insertAfter: Arrayism.insert.insertAfter,
	insertBefore: Arrayism.insert.insertBefore,
	join: Arrayism.join.join,
	joinDiff: Arrayism.join.joinDiff,
	max: Arrayism.math.max,
	min: Arrayism.math.min,
	nth: Arrayism.nth,
	pollute: Arrayism.pollute,
	product: Arrayism.math.product,
	quotient: Arrayism.math.quotient,
	random: Arrayism.random,
	remove: Arrayism.remove.remove,
	removeMany: Arrayism.remove.removeMany,
	replace: Arrayism.replace,
	shuffle: Arrayism.shuffle,
	sum: Arrayism.math.sum,
	swap: Arrayism.swap,
	type: Arrayism.type,
	unique: Arrayism.unique,
	unzipObj: Arrayism.unzipObj,
	walk: Arrayism.walk,
	zipObj: Arrayism.zipObj,
}

module.exports.string = string;
module.exports.array = array;
